AppBundle\Entity\Torre:
    type: entity
    table: torres
    indexes:
        fk_torre_usuario:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombret:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        descripciont:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
